import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  MatButtonModule,
  MatToolbarModule,
  MatIconModule,
  MatBadgeModule,
  MatSidenavModule,
  MatListModule,
  MatGridListModule,
  MatFormFieldModule,
  MatInputModule,
  MatSelectModule,
  MatRadioModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatChipsModule,
  MatTooltipModule,
  MatTableModule,
  MatPaginatorModule,
  MatSliderModule,
  MatMenuModule,
  MatTreeModule,
  MatSnackBarModule,
  MatCheckboxModule,
  MatProgressBarModule,
  MatSortModule,
  MatBottomSheetModule,
  MatProgressSpinnerModule,
  MatAutocompleteModule
} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    MatButtonModule,
    MatToolbarModule,
    MatIconModule,
    MatSidenavModule,
    MatBadgeModule,
    MatListModule,
    MatGridListModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatRadioModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatChipsModule,
    MatTooltipModule,
    MatTableModule,
    MatPaginatorModule,
    MatSliderModule,
    MatMenuModule,
    MatTreeModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatProgressBarModule,
    MatSortModule,
    MatBottomSheetModule,
    MatProgressSpinnerModule,
    MatAutocompleteModule
  ],
  exports: [
    MatButtonModule,
    MatToolbarModule,
    MatIconModule,
    MatSidenavModule,
    MatBadgeModule,
    MatListModule,
    MatGridListModule,
    MatInputModule,
    MatFormFieldModule,
    MatSelectModule,
    MatRadioModule,
    MatDatepickerModule,
    MatChipsModule,
    MatTooltipModule,
    MatTableModule,
    MatPaginatorModule,
    MatSliderModule,
    MatMenuModule,
    MatTreeModule,
    MatSnackBarModule,
    MatCheckboxModule,
    MatProgressBarModule,
    MatSortModule,
    MatBottomSheetModule,
    MatProgressSpinnerModule,
    MatAutocompleteModule
  ],
  providers: [
    MatDatepickerModule,
  ]
})

export class AngularMaterialModule { }
